# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TheWitcherDialog
                                 A QGIS plugin
 Import raster and vector data from The Witcher:Wild Hunt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-19
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Dominik Jęśko
        email                : dominikjesko99@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'witcher_dialog_base_vector.ui'))


class TheWitcherDialogVector(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TheWitcherDialogVector, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.select_all.clicked.connect(self.selectAll)
        self.unselect_all.clicked.connect(self.unselectAll)
        self.select_all2.clicked.connect(self.selectAll2)
        self.unselect_all2.clicked.connect(self.unselectAll2)

    def selectAll(self, state):
        for child in self.groupBox.findChildren(QtWidgets.QCheckBox):
            child.setChecked(True)

    def unselectAll(self, state):
        for child in self.groupBox.findChildren(QtWidgets.QCheckBox):
            child.setChecked(False)

    def selectAll2(self, state):
        for child in self.groupBox2.findChildren(QtWidgets.QCheckBox):
            child.setChecked(True)

    def unselectAll2(self, state):
        for child in self.groupBox2.findChildren(QtWidgets.QCheckBox):
            child.setChecked(False)
